// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Siffrum.Ecom.DAL.Context;

#nullable disable

namespace Siffrum.Ecom.DAL.Migrations
{
    [DbContext(typeof(ApiDbContext))]
    [Migration("20260521105000_FixActivityLogsJsonColumns")]
    partial class FixActivityLogsJsonColumns
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            // Fixes old_values and new_values column types from jsonb to text
#pragma warning restore 612, 618
        }
    }
}
