using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace Siffrum.Ecom.DAL.Migrations
{
    public partial class AddUserSupportReplyTable : Migration
    {
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.Sql(@"
                DO $$
                BEGIN
                    -- Create user_support_replies table if not exists
                    IF NOT EXISTS (SELECT 1 FROM information_schema.tables WHERE table_name = 'user_support_replies') THEN
                        CREATE TABLE user_support_replies (
                            id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                            support_request_id bigint NOT NULL,
                            message character varying(2000) NOT NULL,
                            sender_role character varying(20) NOT NULL,
                            sender_id bigint NOT NULL,
                            created_by text,
                            updated_by text,
                            created_at timestamp with time zone DEFAULT NOW(),
                            updated_at timestamp with time zone,
                            CONSTRAINT ""FK_user_support_replies_UserSupportRequest_support_request_id""
                                FOREIGN KEY (support_request_id) REFERENCES ""UserSupportRequest""(id) ON DELETE CASCADE
                        );
                    END IF;
                END
                $$;

                CREATE INDEX IF NOT EXISTS ""IX_user_support_replies_support_request_id""
                    ON user_support_replies (support_request_id);
            ");
        }

        protected override void Down(MigrationBuilder migrationBuilder)
        {
            // Safe: do not drop in production
        }
    }
}
