using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace Siffrum.Ecom.DAL.Migrations
{
    public partial class AddInAppNotifications : Migration
    {
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.Sql(@"
                -- ══════ in_app_notifications (safe / idempotent) ══════
                CREATE TABLE IF NOT EXISTS in_app_notifications (
                    id              bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    recipient_type  integer        NOT NULL,
                    recipient_id    bigint,
                    title           text           NOT NULL DEFAULT '',
                    message         text           NOT NULL DEFAULT '',
                    type            text           NOT NULL DEFAULT '',
                    reference_id    text,
                    is_read         boolean        NOT NULL DEFAULT FALSE,
                    read_at         timestamp with time zone,
                    created_at      timestamp with time zone DEFAULT NOW(),
                    updated_at      timestamp with time zone
                );

                -- Indexes (IF NOT EXISTS keeps it safe on re-run)
                CREATE INDEX IF NOT EXISTS ix_in_app_notifications_recipient
                    ON in_app_notifications (recipient_type, recipient_id, is_read);

                CREATE INDEX IF NOT EXISTS ix_in_app_notifications_created
                    ON in_app_notifications (created_at DESC);
            ");
        }

        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.Sql(@"
                DROP TABLE IF EXISTS in_app_notifications;
            ");
        }
    }
}
