// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Siffrum.Ecom.DAL.Context;

#nullable disable

namespace Siffrum.Ecom.DAL.Migrations
{
    [DbContext(typeof(ApiDbContext))]
    [Migration("20260521102057_AddActivityLogsTable")]
    partial class AddActivityLogsTable
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            // Activity logs table is created via raw SQL in the Up() method
            // This migration adds the activity_logs table with all indexes
#pragma warning restore 612, 618
        }
    }
}
