using System;
using Microsoft.EntityFrameworkCore.Migrations;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Siffrum.Ecom.DAL.Migrations
{
    public partial class AddComplaintMessages : Migration
    {
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            // Only create the complaint_messages table — all other index
            // changes detected by EF are skipped to keep prod safe.
            migrationBuilder.Sql(@"
                CREATE TABLE IF NOT EXISTS complaint_messages (
                    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    complaint_id    BIGINT       NOT NULL,
                    sender_type     VARCHAR(20)  NOT NULL,
                    sender_id       BIGINT       NOT NULL,
                    message         TEXT,
                    image_url       VARCHAR(500),
                    created_at      TIMESTAMP WITH TIME ZONE,
                    updated_at      TIMESTAMP WITH TIME ZONE,
                    created_by      TEXT,
                    updated_by      TEXT,
                    CONSTRAINT ""FK_complaint_messages_order_complaints_complaint_id""
                        FOREIGN KEY (complaint_id) REFERENCES order_complaints(id) ON DELETE CASCADE
                );
            ");

            migrationBuilder.Sql(@"
                CREATE INDEX IF NOT EXISTS ""IX_complaint_messages_complaint_id""
                    ON complaint_messages (complaint_id);
            ");
        }

        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.Sql(@"DROP TABLE IF EXISTS complaint_messages;");
        }
    }
}
