// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Siffrum.Ecom.DAL.Context;

#nullable disable

namespace Siffrum.Ecom.DAL.Migrations
{
    [DbContext(typeof(ApiDbContext))]
    [Migration("20260521160000_AddDeliverySpeedToBanners")]
    partial class AddDeliverySpeedToBanners
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            // This migration adds is_normal and is_express columns to banners table
            // The actual column creation is done via raw SQL in the migration's Up() method

#pragma warning restore 612, 618
        }
    }
}
