// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Siffrum.Ecom.DAL.Context;

#nullable disable

namespace Siffrum.Ecom.DAL.Migrations
{
    [DbContext(typeof(ApiDbContext))]
    [Migration("20260411183000_AddToppingSuggestedBySellerId")]
    partial class AddToppingSuggestedBySellerId
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            // This migration only adds a single nullable column.
            // The full target model is captured in ApiDbContextModelSnapshot.cs.
            // Intentionally left minimal — EF Core uses the snapshot for model diffing.
#pragma warning restore 612, 618
        }
    }
}
