using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace Siffrum.Ecom.DAL.Migrations
{
    public partial class FixMissingSellerColumns : Migration
    {
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.Sql(@"
                DO $$
                BEGIN
                    -- ══════ sellers ══════
                    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='sellers' AND column_name='pending_latitude') THEN
                        ALTER TABLE sellers ADD COLUMN pending_latitude numeric;
                    END IF;

                    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='sellers' AND column_name='pending_longitude') THEN
                        ALTER TABLE sellers ADD COLUMN pending_longitude numeric;
                    END IF;

                    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='sellers' AND column_name='location_status') THEN
                        ALTER TABLE sellers ADD COLUMN location_status smallint NOT NULL DEFAULT 0;
                    END IF;

                    -- ══════ categories ══════
                    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='categories' AND column_name='suggested_by_seller_id') THEN
                        ALTER TABLE categories ADD COLUMN suggested_by_seller_id bigint;
                    END IF;

                    -- ══════ delivery_boys ══════
                    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='delivery_boys' AND column_name='seller_id') THEN
                        ALTER TABLE delivery_boys ADD COLUMN seller_id bigint;
                    END IF;

                    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='delivery_boys' AND column_name='aadhaar_number') THEN
                        ALTER TABLE delivery_boys ADD COLUMN aadhaar_number character varying(12);
                    END IF;

                    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='delivery_boys' AND column_name='aadhaar_photo') THEN
                        ALTER TABLE delivery_boys ADD COLUMN aadhaar_photo text;
                    END IF;

                    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='delivery_boys' AND column_name='driving_license_photo') THEN
                        ALTER TABLE delivery_boys ADD COLUMN driving_license_photo text;
                    END IF;

                    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='delivery_boys' AND column_name='passport_photo') THEN
                        ALTER TABLE delivery_boys ADD COLUMN passport_photo text;
                    END IF;

                    -- ══════ deliveries ══════
                    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='deliveries' AND column_name='commission') THEN
                        ALTER TABLE deliveries ADD COLUMN commission numeric NOT NULL DEFAULT 0;
                    END IF;

                    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='deliveries' AND column_name='distance_in_km') THEN
                        ALTER TABLE deliveries ADD COLUMN distance_in_km double precision NOT NULL DEFAULT 0;
                    END IF;

                    -- ══════ orders ══════
                    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name='orders' AND column_name='seller_id') THEN
                        ALTER TABLE orders ADD COLUMN seller_id bigint;
                    END IF;
                END
                $$;

                -- ══════ cash_collections (entire table) ══════
                CREATE TABLE IF NOT EXISTS cash_collections (
                    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    seller_id bigint NOT NULL,
                    delivery_boy_id bigint NOT NULL,
                    amount decimal(18,2) NOT NULL DEFAULT 0,
                    status integer NOT NULL DEFAULT 0,
                    collected_at timestamp with time zone,
                    remarks text,
                    date_from timestamp with time zone NOT NULL DEFAULT NOW(),
                    date_to timestamp with time zone NOT NULL DEFAULT NOW(),
                    created_at timestamp with time zone,
                    updated_at timestamp with time zone,
                    created_by text,
                    updated_by text,
                    CONSTRAINT ""FK_cash_collections_delivery_boys_delivery_boy_id""
                        FOREIGN KEY (delivery_boy_id) REFERENCES delivery_boys(id) ON DELETE CASCADE
                );

                CREATE INDEX IF NOT EXISTS ""IX_cash_collections_delivery_boy_id""
                    ON cash_collections (delivery_boy_id);

                -- ══════ order_complaints (entire table) ══════
                CREATE TABLE IF NOT EXISTS order_complaints (
                    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    order_id bigint NOT NULL,
                    user_id bigint NOT NULL,
                    seller_id bigint,
                    email character varying(255) NOT NULL,
                    message text NOT NULL,
                    status integer NOT NULL DEFAULT 0,
                    seller_reply text,
                    replied_at timestamp with time zone,
                    created_at timestamp with time zone,
                    updated_at timestamp with time zone,
                    created_by text,
                    updated_by text,
                    CONSTRAINT ""FK_order_complaints_orders_order_id""
                        FOREIGN KEY (order_id) REFERENCES orders(id) ON DELETE CASCADE
                );

                CREATE INDEX IF NOT EXISTS ""IX_order_complaints_order_id""
                    ON order_complaints (order_id);
            ");
        }

        protected override void Down(MigrationBuilder migrationBuilder)
        {

        }
    }
}
